// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order/order.proto

package mu_micro_book_srv_orders

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	BookId               int64    `protobuf:"varint,2,opt,name=bookId,proto3" json:"bookId,omitempty"`
	OrderId              int64    `protobuf:"varint,3,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderRequest) Reset()         { *m = OrderRequest{} }
func (m *OrderRequest) String() string { return proto.CompactTextString(m) }
func (*OrderRequest) ProtoMessage()    {}
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{0}
}

func (m *OrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderRequest.Unmarshal(m, b)
}
func (m *OrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderRequest.Marshal(b, m, deterministic)
}
func (m *OrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderRequest.Merge(m, src)
}
func (m *OrderRequest) XXX_Size() int {
	return xxx_messageInfo_OrderRequest.Size(m)
}
func (m *OrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderRequest proto.InternalMessageInfo

func (m *OrderRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *OrderRequest) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *OrderRequest) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type Order struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	BookId               int64    `protobuf:"varint,3,opt,name=bookId,proto3" json:"bookId,omitempty"`
	InvHistoryId         int64    `protobuf:"varint,4,opt,name=invHistoryId,proto3" json:"invHistoryId,omitempty"`
	State                int64    `protobuf:"varint,5,opt,name=state,proto3" json:"state,omitempty"`
	CreatedTime          int64    `protobuf:"varint,6,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	UpdatedTime          int64    `protobuf:"varint,7,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{1}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Order) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Order) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *Order) GetInvHistoryId() int64 {
	if m != nil {
		return m.InvHistoryId
	}
	return 0
}

func (m *Order) GetState() int64 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *Order) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *Order) GetUpdatedTime() int64 {
	if m != nil {
		return m.UpdatedTime
	}
	return 0
}

type OrderResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Order                *Order   `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderResponse) Reset()         { *m = OrderResponse{} }
func (m *OrderResponse) String() string { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()    {}
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{2}
}

func (m *OrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResponse.Unmarshal(m, b)
}
func (m *OrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResponse.Marshal(b, m, deterministic)
}
func (m *OrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResponse.Merge(m, src)
}
func (m *OrderResponse) XXX_Size() int {
	return xxx_messageInfo_OrderResponse.Size(m)
}
func (m *OrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResponse proto.InternalMessageInfo

func (m *OrderResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *OrderResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *OrderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_986e030a471601a2, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterType((*OrderRequest)(nil), "mu.micro.book.srv.orders.OrderRequest")
	proto.RegisterType((*Order)(nil), "mu.micro.book.srv.orders.Order")
	proto.RegisterType((*OrderResponse)(nil), "mu.micro.book.srv.orders.OrderResponse")
	proto.RegisterType((*Error)(nil), "mu.micro.book.srv.orders.Error")
}

func init() { proto.RegisterFile("proto/order/order.proto", fileDescriptor_986e030a471601a2) }

var fileDescriptor_986e030a471601a2 = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xbb, 0x4e, 0xf3, 0x30,
	0x14, 0xfe, 0x93, 0x34, 0x69, 0xff, 0xd3, 0xc2, 0x60, 0x21, 0xb0, 0x58, 0xa8, 0x32, 0x00, 0x93,
	0x91, 0x5a, 0xf1, 0x08, 0x08, 0xb2, 0x80, 0x64, 0x31, 0x74, 0x61, 0x68, 0xe3, 0x33, 0x58, 0xd0,
	0xba, 0xd8, 0x4e, 0x11, 0x4f, 0xc2, 0xf3, 0x30, 0xf0, 0x5e, 0xc8, 0xc7, 0x2d, 0x4a, 0x87, 0xd2,
	0x85, 0x25, 0xf2, 0x77, 0xf1, 0x77, 0x2e, 0x31, 0x9c, 0x2c, 0xad, 0xf1, 0xe6, 0xca, 0x58, 0x85,
	0x36, 0x7e, 0x05, 0x31, 0x8c, 0xcf, 0x1b, 0x31, 0xd7, 0xb5, 0x35, 0x62, 0x66, 0xcc, 0xb3, 0x70,
	0x76, 0x25, 0x48, 0x76, 0xe5, 0x04, 0x06, 0x0f, 0xe1, 0x24, 0xf1, 0xb5, 0x41, 0xe7, 0xd9, 0x31,
	0x14, 0x8d, 0x43, 0x5b, 0x29, 0x9e, 0x0c, 0x93, 0xcb, 0x4c, 0xae, 0x51, 0xe0, 0xc3, 0xd5, 0x4a,
	0xf1, 0x34, 0xf2, 0x11, 0x31, 0x0e, 0x5d, 0x4a, 0xaa, 0x14, 0xcf, 0x48, 0xd8, 0xc0, 0xf2, 0x2b,
	0x81, 0x9c, 0xa2, 0xd9, 0x21, 0xa4, 0x7a, 0x93, 0x97, 0x6a, 0xd5, 0xaa, 0x91, 0xee, 0xa8, 0x91,
	0x6d, 0xd5, 0x28, 0x61, 0xa0, 0x17, 0xab, 0x3b, 0xed, 0xbc, 0xb1, 0xef, 0x95, 0xe2, 0x1d, 0x52,
	0xb7, 0x38, 0x76, 0x04, 0xb9, 0xf3, 0x53, 0x8f, 0x3c, 0x27, 0x31, 0x02, 0x36, 0x84, 0x7e, 0x6d,
	0x71, 0xea, 0x51, 0x3d, 0xea, 0x39, 0xf2, 0x82, 0xb4, 0x36, 0x15, 0x1c, 0xcd, 0x52, 0xfd, 0x38,
	0xba, 0xd1, 0xd1, 0xa2, 0xca, 0x8f, 0x04, 0x0e, 0xd6, 0x2b, 0x72, 0x4b, 0xb3, 0x70, 0x18, 0x66,
	0x76, 0x4d, 0x5d, 0xa3, 0x73, 0x34, 0x54, 0x4f, 0x6e, 0x20, 0xbb, 0x86, 0x1c, 0xad, 0x35, 0x96,
	0x06, 0xeb, 0x8f, 0xce, 0xc4, 0xae, 0xbd, 0x8b, 0x9b, 0x60, 0x93, 0xd1, 0x1d, 0xae, 0x11, 0x4d,
	0x73, 0xff, 0x7a, 0x2d, 0x36, 0x12, 0xdd, 0xe5, 0x18, 0x72, 0x8a, 0x61, 0x0c, 0x3a, 0xb5, 0x51,
	0x48, 0xdd, 0xe4, 0x92, 0xce, 0x61, 0x99, 0x0a, 0xfd, 0x54, 0xbf, 0x50, 0x2f, 0xff, 0xe5, 0x1a,
	0x8d, 0x3e, 0x13, 0x28, 0x28, 0xc5, 0xb1, 0x09, 0x64, 0xf7, 0xf8, 0xc6, 0xce, 0xf7, 0x95, 0x8b,
	0x4f, 0xe3, 0xf4, 0x62, 0xaf, 0x2f, 0xee, 0xa7, 0xfc, 0xc7, 0x9e, 0xa0, 0x77, 0x8b, 0x3e, 0xfe,
	0xfd, 0xbf, 0x8f, 0x9f, 0x15, 0xf4, 0xaa, 0xc7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x68,
	0xb4, 0x7c, 0xf0, 0x02, 0x00, 0x00,
}
