// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/inventory/inventory.proto

package mu_micro_book_srv_inventory

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Inv struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId               int64    `protobuf:"varint,2,opt,name=bookId,proto3" json:"bookId,omitempty"`
	UnitPrice            int64    `protobuf:"varint,3,opt,name=unitPrice,proto3" json:"unitPrice,omitempty"`
	Stock                int64    `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	Version              int64    `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	CreatedTime          int64    `protobuf:"varint,6,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	UpdatedTime          int64    `protobuf:"varint,7,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Inv) Reset()         { *m = Inv{} }
func (m *Inv) String() string { return proto.CompactTextString(m) }
func (*Inv) ProtoMessage()    {}
func (*Inv) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{0}
}

func (m *Inv) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inv.Unmarshal(m, b)
}
func (m *Inv) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inv.Marshal(b, m, deterministic)
}
func (m *Inv) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inv.Merge(m, src)
}
func (m *Inv) XXX_Size() int {
	return xxx_messageInfo_Inv.Size(m)
}
func (m *Inv) XXX_DiscardUnknown() {
	xxx_messageInfo_Inv.DiscardUnknown(m)
}

var xxx_messageInfo_Inv proto.InternalMessageInfo

func (m *Inv) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Inv) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *Inv) GetUnitPrice() int64 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *Inv) GetStock() int64 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *Inv) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Inv) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *Inv) GetUpdatedTime() int64 {
	if m != nil {
		return m.UpdatedTime
	}
	return 0
}

type InvHistory struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId               int64    `protobuf:"varint,2,opt,name=bookId,proto3" json:"bookId,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	State                int64    `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvHistory) Reset()         { *m = InvHistory{} }
func (m *InvHistory) String() string { return proto.CompactTextString(m) }
func (*InvHistory) ProtoMessage()    {}
func (*InvHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{1}
}

func (m *InvHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvHistory.Unmarshal(m, b)
}
func (m *InvHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvHistory.Marshal(b, m, deterministic)
}
func (m *InvHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvHistory.Merge(m, src)
}
func (m *InvHistory) XXX_Size() int {
	return xxx_messageInfo_InvHistory.Size(m)
}
func (m *InvHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_InvHistory.DiscardUnknown(m)
}

var xxx_messageInfo_InvHistory proto.InternalMessageInfo

func (m *InvHistory) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InvHistory) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *InvHistory) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *InvHistory) GetState() int64 {
	if m != nil {
		return m.State
	}
	return 0
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type InventoryRequest struct {
	BookId               int64    `protobuf:"varint,1,opt,name=bookId,proto3" json:"bookId,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	HistoryId            int64    `protobuf:"varint,3,opt,name=historyId,proto3" json:"historyId,omitempty"`
	HistoryState         int32    `protobuf:"varint,4,opt,name=historyState,proto3" json:"historyState,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InventoryRequest) Reset()         { *m = InventoryRequest{} }
func (m *InventoryRequest) String() string { return proto.CompactTextString(m) }
func (*InventoryRequest) ProtoMessage()    {}
func (*InventoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{3}
}

func (m *InventoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventoryRequest.Unmarshal(m, b)
}
func (m *InventoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventoryRequest.Marshal(b, m, deterministic)
}
func (m *InventoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventoryRequest.Merge(m, src)
}
func (m *InventoryRequest) XXX_Size() int {
	return xxx_messageInfo_InventoryRequest.Size(m)
}
func (m *InventoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InventoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InventoryRequest proto.InternalMessageInfo

func (m *InventoryRequest) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *InventoryRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *InventoryRequest) GetHistoryId() int64 {
	if m != nil {
		return m.HistoryId
	}
	return 0
}

func (m *InventoryRequest) GetHistoryState() int32 {
	if m != nil {
		return m.HistoryState
	}
	return 0
}

type InventoryResponse struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Inv                  *Inv        `protobuf:"bytes,3,opt,name=inv,proto3" json:"inv,omitempty"`
	InvH                 *InvHistory `protobuf:"bytes,4,opt,name=invH,proto3" json:"invH,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *InventoryResponse) Reset()         { *m = InventoryResponse{} }
func (m *InventoryResponse) String() string { return proto.CompactTextString(m) }
func (*InventoryResponse) ProtoMessage()    {}
func (*InventoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{4}
}

func (m *InventoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventoryResponse.Unmarshal(m, b)
}
func (m *InventoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventoryResponse.Marshal(b, m, deterministic)
}
func (m *InventoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventoryResponse.Merge(m, src)
}
func (m *InventoryResponse) XXX_Size() int {
	return xxx_messageInfo_InventoryResponse.Size(m)
}
func (m *InventoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InventoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InventoryResponse proto.InternalMessageInfo

func (m *InventoryResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *InventoryResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *InventoryResponse) GetInv() *Inv {
	if m != nil {
		return m.Inv
	}
	return nil
}

func (m *InventoryResponse) GetInvH() *InvHistory {
	if m != nil {
		return m.InvH
	}
	return nil
}

func init() {
	proto.RegisterType((*Inv)(nil), "mu.micro.book.srv.inventory.Inv")
	proto.RegisterType((*InvHistory)(nil), "mu.micro.book.srv.inventory.InvHistory")
	proto.RegisterType((*Error)(nil), "mu.micro.book.srv.inventory.Error")
	proto.RegisterType((*InventoryRequest)(nil), "mu.micro.book.srv.inventory.InventoryRequest")
	proto.RegisterType((*InventoryResponse)(nil), "mu.micro.book.srv.inventory.InventoryResponse")
}

func init() { proto.RegisterFile("proto/inventory/inventory.proto", fileDescriptor_d77ba5e53e1c0527) }

var fileDescriptor_d77ba5e53e1c0527 = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x25, 0x6d, 0xd3, 0xd2, 0x29, 0x42, 0x30, 0x42, 0xab, 0x08, 0x56, 0xa2, 0xf2, 0x05, 0x2e,
	0x18, 0x29, 0x7b, 0x41, 0xe2, 0x88, 0x90, 0x36, 0x37, 0xe4, 0xe5, 0x07, 0xda, 0x78, 0x00, 0xb3,
	0xad, 0x5d, 0x6c, 0xc7, 0x12, 0x77, 0xfe, 0x8b, 0xdf, 0xe0, 0xc8, 0xa7, 0xa0, 0x4c, 0xd2, 0xb4,
	0x3d, 0xb0, 0xbb, 0x97, 0xbd, 0xf9, 0xbd, 0x79, 0x63, 0xbf, 0x37, 0x93, 0xc0, 0xcb, 0x9d, 0x77,
	0xd1, 0xbd, 0x35, 0x36, 0x91, 0x8d, 0xce, 0xff, 0x3c, 0x9c, 0x24, 0x57, 0xf0, 0xc5, 0xb6, 0x91,
	0x5b, 0x53, 0x7b, 0x27, 0xd7, 0xce, 0x5d, 0xcb, 0xe0, 0x93, 0x1c, 0x24, 0xe2, 0x77, 0x06, 0xe3,
	0xca, 0x26, 0x7c, 0x0c, 0x23, 0xa3, 0x8b, 0x6c, 0x99, 0xbd, 0x1e, 0xab, 0x91, 0xd1, 0x78, 0x06,
	0xd3, 0x56, 0x5d, 0xe9, 0x62, 0xc4, 0x5c, 0x8f, 0xf0, 0x1c, 0xe6, 0x8d, 0x35, 0xf1, 0x93, 0x37,
	0x35, 0x15, 0x63, 0x2e, 0x1d, 0x08, 0x7c, 0x06, 0x79, 0x88, 0xae, 0xbe, 0x2e, 0x26, 0x5c, 0xe9,
	0x00, 0x16, 0x30, 0x4b, 0xe4, 0x83, 0x71, 0xb6, 0xc8, 0x99, 0xdf, 0x43, 0x5c, 0xc2, 0xa2, 0xf6,
	0xb4, 0x8a, 0xa4, 0x3f, 0x9b, 0x2d, 0x15, 0x53, 0xae, 0x1e, 0x53, 0xad, 0xa2, 0xd9, 0xe9, 0x41,
	0x31, 0xeb, 0x14, 0x47, 0x94, 0x58, 0x03, 0x54, 0x36, 0x5d, 0x9a, 0xd0, 0xe6, 0xb9, 0x73, 0x8e,
	0x33, 0x98, 0x36, 0x81, 0x7c, 0xa5, 0xfb, 0x10, 0x3d, 0xea, 0x12, 0xac, 0x22, 0x1d, 0x12, 0xac,
	0x22, 0x89, 0x0b, 0xc8, 0x3f, 0x7a, 0xef, 0x3c, 0x22, 0x4c, 0x6a, 0xa7, 0x89, 0x1f, 0xc8, 0x15,
	0x9f, 0xdb, 0xab, 0x34, 0xc5, 0x95, 0xd9, 0xf0, 0x13, 0x73, 0xd5, 0x23, 0xf1, 0x2b, 0x83, 0x27,
	0xd5, 0x7e, 0xd0, 0x8a, 0x7e, 0x34, 0x14, 0xe2, 0x91, 0x9f, 0xec, 0x3f, 0x7e, 0x46, 0x27, 0x7e,
	0xce, 0x61, 0xfe, 0xad, 0x8b, 0x36, 0x58, 0x3d, 0x10, 0x28, 0xe0, 0x51, 0x0f, 0xae, 0x06, 0xd3,
	0xb9, 0x3a, 0xe1, 0xc4, 0x9f, 0x0c, 0x9e, 0x1e, 0xd9, 0x08, 0x3b, 0x67, 0x03, 0xb5, 0x3b, 0x09,
	0x4d, 0x5d, 0x53, 0x08, 0x6c, 0xe4, 0xa1, 0xda, 0x43, 0x7c, 0x07, 0x39, 0xb5, 0x59, 0xd9, 0xc8,
	0xa2, 0x14, 0xf2, 0x86, 0xcf, 0x47, 0xf2, 0x54, 0x54, 0xd7, 0x80, 0x25, 0x8c, 0x8d, 0x4d, 0xec,
	0x72, 0x51, 0x2e, 0x6f, 0xec, 0xab, 0x6c, 0x52, 0xad, 0x18, 0xdf, 0xc3, 0xc4, 0xd8, 0x74, 0xc9,
	0xce, 0x17, 0xe5, 0xab, 0xdb, 0x9a, 0xfa, 0x35, 0x2b, 0x6e, 0x2a, 0xff, 0x66, 0x30, 0x1f, 0xa2,
	0xe1, 0x57, 0x98, 0x5c, 0xd1, 0x66, 0x83, 0x6f, 0x6e, 0xbb, 0xe4, 0x64, 0x23, 0xcf, 0xe5, 0x5d,
	0xe5, 0xdd, 0xe4, 0xc4, 0x03, 0xfc, 0x0e, 0xb3, 0x0f, 0xce, 0x7e, 0x31, 0x7e, 0x7b, 0xef, 0x6f,
	0xad, 0xa7, 0xfc, 0x0f, 0x5f, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x21, 0x47, 0xc9, 0x9d, 0xe6,
	0x03, 0x00, 0x00,
}
