// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/greeter/payment.proto

package payment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PayReq struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayReq) Reset()         { *m = PayReq{} }
func (m *PayReq) String() string { return proto.CompactTextString(m) }
func (*PayReq) ProtoMessage()    {}
func (*PayReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_402c6e849144c8c4, []int{0}
}

func (m *PayReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayReq.Unmarshal(m, b)
}
func (m *PayReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayReq.Marshal(b, m, deterministic)
}
func (m *PayReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayReq.Merge(m, src)
}
func (m *PayReq) XXX_Size() int {
	return xxx_messageInfo_PayReq.Size(m)
}
func (m *PayReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PayReq.DiscardUnknown(m)
}

var xxx_messageInfo_PayReq proto.InternalMessageInfo

func (m *PayReq) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *PayReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type PayResp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Success              string   `protobuf:"bytes,2,opt,name=success,proto3" json:"success,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayResp) Reset()         { *m = PayResp{} }
func (m *PayResp) String() string { return proto.CompactTextString(m) }
func (*PayResp) ProtoMessage()    {}
func (*PayResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_402c6e849144c8c4, []int{1}
}

func (m *PayResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayResp.Unmarshal(m, b)
}
func (m *PayResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayResp.Marshal(b, m, deterministic)
}
func (m *PayResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayResp.Merge(m, src)
}
func (m *PayResp) XXX_Size() int {
	return xxx_messageInfo_PayResp.Size(m)
}
func (m *PayResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PayResp.DiscardUnknown(m)
}

var xxx_messageInfo_PayResp proto.InternalMessageInfo

func (m *PayResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PayResp) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

func (m *PayResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*PayReq)(nil), "PayReq")
	proto.RegisterType((*PayResp)(nil), "PayResp")
}

func init() { proto.RegisterFile("proto/greeter/payment.proto", fileDescriptor_402c6e849144c8c4) }

var fileDescriptor_402c6e849144c8c4 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0xb1, 0xae, 0x82, 0x40,
	0x10, 0x45, 0x1f, 0x0f, 0x05, 0x9d, 0xc2, 0x98, 0xad, 0x36, 0xd8, 0x18, 0x2a, 0x0b, 0x03, 0x89,
	0xb6, 0xfe, 0x00, 0x1d, 0xc1, 0x2f, 0x58, 0x87, 0x09, 0xb1, 0x80, 0xc5, 0xd9, 0xc5, 0x84, 0xbf,
	0x37, 0x0c, 0xd0, 0xcd, 0xbd, 0x37, 0x27, 0x73, 0xe0, 0xd4, 0xb3, 0xf5, 0x36, 0x6f, 0x98, 0xc8,
	0x13, 0xe7, 0xbd, 0x19, 0x5b, 0xea, 0x7c, 0x26, 0x6d, 0xfa, 0x80, 0xa8, 0x34, 0x63, 0x45, 0x1f,
	0xa5, 0x21, 0xb6, 0x5c, 0x13, 0x17, 0xb5, 0x0e, 0xce, 0xc1, 0x65, 0x5f, 0xad, 0x71, 0x5a, 0x0c,
	0xa2, 0x1d, 0x3a, 0xaf, 0xff, 0xe7, 0x65, 0x89, 0x69, 0x01, 0xb1, 0xd0, 0xae, 0x57, 0x0a, 0x36,
	0x68, 0x6b, 0x12, 0x76, 0x5b, 0xc9, 0x3d, 0x81, 0x6e, 0x40, 0x24, 0xe7, 0x56, 0x70, 0x89, 0xea,
	0x08, 0x61, 0xeb, 0x1a, 0x1d, 0x4a, 0x3b, 0x9d, 0xb7, 0x2b, 0x1c, 0xca, 0xd9, 0xec, 0x49, 0xfc,
	0x7d, 0x23, 0xa9, 0x04, 0xc2, 0xd2, 0x8c, 0x2a, 0xce, 0x66, 0xc1, 0x64, 0x97, 0x2d, 0xbf, 0xd2,
	0xbf, 0x57, 0x24, 0xf6, 0xf7, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x63, 0x46, 0x39, 0x13, 0xdc,
	0x00, 0x00, 0x00,
}
